Visiting Library Button
pplg-smk-metland/metschoo-library pull request #79
Opened 2024-12-13 02:29 UTC by Adreon19

2024-12-13 03:14 UTC, Klrfl commented
tasks:
- [x] update UI to checkin/checkout
- [x] add a new table to log checkin/checkout events
- [ ] add checkin/checkout functionality in app

2024-12-13 03:15 UTC, Adreon19 commented
yeay

2024-12-13 03:22 UTC, Adreon19 commented
![Uploading bug.gif…]()

2024-12-13 03:23 UTC, Adreon19 commented
![bug](https://github.com/user-attachments/assets/b1a0a4fa-1ad5-40bc-8b8f-86bdbbb5b937)

2024-12-13 07:51 UTC, Adreon19 commented
![knee](https://github.com/user-attachments/assets/e149fbd9-0c69-4fce-ae46-c06e24183ace)

2024-12-14 04:03 UTC, Klrfl requested changes

2024-12-14 04:03 UTC, Klrfl commented on pages/profil/index.vue
> +      <h2>Kunjungan</h2>
Judul sama paragrafnya lebih playful ya. Gapapa ditambahin apa dulu nanti gua confirm lagi sama bu Aka

2024-12-14 04:03 UTC, Klrfl commented on pages/profil/index.vue
> +async function enterLibrary() {
sebenarnya lebih bagus kalau dibuat parameter disini (`enterLibrary(isPresent: boolean)`).. biar ga usah pake .value, tapi gini juga gapapa

2024-12-16 02:24 UTC, Adreon19 commented on pages/profil/index.vue
> +async function enterLibrary() {
jadi ganti apa gk

2024-12-16 02:26 UTC, Adreon19 commented on pages/profil/index.vue
> +      <h2>Kunjungan</h2>
okee, ada saran ndak

2024-12-16 02:29 UTC, Adreon19 commented on pages/profil/index.vue
> +      <h2>Kunjungan</h2>
oh gua ada ide, bentar

2024-12-16 02:39 UTC, Klrfl commented on pages/profil/index.vue
> +async function enterLibrary() {
ganti ajah

2024-12-16 02:39 UTC, Klrfl approved these changes
mantab

2024-12-16 04:04 UTC, Klrfl commented
Eh tunggu sebentar. Kalau user checkin, keluar dari halaman terus balik lagi, statusnya bakal masih keluar. Fix is on the way

2024-12-16 04:23 UTC, Klrfl commented
![Screenshot (96)](https://github.com/user-attachments/assets/2a778ff8-b9f1-4393-abf1-1e90157e6990)

2024-12-18 04:52 UTC, Klrfl commented on pages/admin/index.vue
> +        <Column field="pengguna.nama" header="Pengguna" />
Yea that

2024-12-18 04:52 UTC, Adreon19 commented on pages/admin/index.vue
> +        <Column field="pengguna.nama" header="Pengguna" />
yea that

2024-12-23 01:10 UTC, merged